stages:
  data_ingestion:
    cmd: python src/CancerClassification/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CancerClassification/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Data 

  prepare_base_model:
    cmd: python src/CancerClassification/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/CancerClassification/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - LEARNING_RATE
      - WEIGHTS
    outs:
      - artifacts/prepare_base_model 
  
  training:
    cmd: python src/CancerClassification/pipeline/stage_03_model_trainer.py
    deps:
      - src/CancerClassification/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/Data
      - artifacts/prepare_base_model
    params:
      - BATCH_SIZE
      - EPOCHS
      - IMAGE_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5
  
  evaluation:
    cmd: python src/CancerClassification/pipeline/stage_04_model_evaluation.py
    deps:
      - src/CancerClassification/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/training/model.h5
      - artifacts/data_ingestion/Data
    params:
      - BATCH_SIZE
      - IMAGE_SIZE
    metrics:
      - scores.json:
          cache: false