artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: mohamedhanyyy/chest-ctscan-images
  local_data_file: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion